 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"

 env:
     - PLATFORMIO_CI_SRC=./arduboy/buttons

 install:
     - pip install -U platformio

 script:
     - platformio ci --project-conf=./arduboy/buttons/platformio.ini
