 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"

 env:
     - PLATFORMIO_CI_SRC=apps/bin2dec/src/bin2dec.ino
     - PLATFORMIO_CI_SRC=apps/timer/src/timer.ino
     - PLATFORMIO_CI_SRC=demos/buttons/src/buttons.ino
     - PLATFORMIO_CI_SRC=demos/graphics/src/graphics.ino
     - PLATFORMIO_CI_SRC=games/pong/src/pong.ino

 install:
     - pip install -U platformio
     - platformio lib install "Arduboy"
     - platformio lib install "Arduboy2"

 script:
     - platformio ci --board=arduboy
