 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"

 env:
     - PLATFORMIO_CI_SRC=arduboy/buttons/src/buttons.ino
     - PLATFORMIO_CI_SRC=arduboy/bin2dec/src/bin2dec.ino

 install:
     - pip install -U platformio
     - platformio lib install "Arduboy"

 script:
     - platformio ci --board=arduboy
