 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"

 env:
     - PLATFORMIO_CI_SRC=buttons/src/buttons.ino
     - PLATFORMIO_CI_SRC=bin2dec/src/bin2dec.ino
     - PLATFORMIO_CI_SRC=timer/src/timer.ino

 install:
     - pip install -U platformio
     - platformio lib install "Arduboy"

 script:
     - platformio ci --board=arduboy
